### ISSUE TITLE
Utility doesn't work

### ISSUE THREAD

**Issue by jordanbonilla** [RunGp/Nvidiux#1]
I type: sudo nvidiux
 and get:
 Echec chargement des parametres Gpu Error Code:34

I have all dependencies.
Using Ubuntu 14.03
3 x 780 ti

**Comment by RunGp** [comment]
hello
No need to launch nvidiux with sudo

Error 34 = bad return of lspci

Give me the return of command 
lspci -vnn | grep NVIDIA | grep -v Audio

**Comment by jordanbonilla** [comment]
Thank you for the reply.

Output is: 

01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GK110B [GeForce GTX 780 Ti] [10de:100a](rev a1) (prog-if 00 [VGA controller])
02:00.0 VGA compatible controller [0300]: NVIDIA Corporation GK110B [GeForce GTX 780 Ti] [10de:100a](rev a1) (prog-if 00 [VGA controller])
03:00.0 VGA compatible controller [0300]: NVIDIA Corporation GK110B [GeForce GTX 780 Ti] [10de:100a](rev a1) (prog-if 00 [VGA controller])
    Subsystem: NVIDIA Corporation Device [10de:1051]
    Subsystem: NVIDIA Corporation Device [10de:1051]

same message if I use "python nvidiux.py" or "nvidiux"
Am I entering an incorrect command?

**Comment by RunGp** [comment]
Hello
your command is correct 

lspci return your 3 card and 2 times this unknow device "Subsystem: NVIDIA Corporation Device [10de:1051]" 
nvidiux crash because is not recognize this device 
Do you have other nvidia gpu/device on this pc ?

**Comment by jordanbonilla** [comment]
No, I do not have any other nvidia devices attached. Perhaps this is caused by the custom skyn3t BIOS I put on the cards.

**Comment by RunGp** [comment]
Ok this "fantomatic" nvdia device is strange

I fix the bug  try the new version 0.98d
Now if nvidiux detect a Nvidia device  identified as not being a nvidia geforce GPU it will be ignored

**Comment by RunGp** [comment]
No response 
Nvidiux works ? can i add GeForce GTX 780 Ti in compatibility white list ?
I close this thread Sunday if no response

**Comment by jordanbonilla** [comment]
It works! Thank you.

**Comment by RunGp** [comment]
Ok  i add GTX 780 Ti in white list :)
