### ISSUE TITLE
Trying to package nvidiux, having a few issues.

### ISSUE THREAD

**Issue by andrewschott** [RunGp/Nvidiux#10]
OK, firstly for some reason the error dialogues are in French.  Any way to force English, or use a system default language?

Secondly (unsure how obvious this is to fix due to language barrier) I get two dialogues.  

1) Overlaid on the Nvidiux splash:
La configuration du fichier xorg n'est pas effectu!
Entrer votre mot de passe administrator pour effectuer la configuration

2) After clicking the OK button I come to this:
Votre mot de passe est incorrect
Error Code:7

Thanks for any aid rendered, as I would love to get a EL7 package rolled up, and then a Fedora one.

Thanks again,
Andrew

**Comment by RunGp** [comment]
hello

for 1)
Normally nvidiux use default system language by default if possible or english as failbak
you can force en langage 
edit ~/.nvidiux/conf.xml
add en_EN in lang section
Edit : if nvidiux doesn't start the conf file is not write... resolve 2) before and give your administrator password and retry
If nvidiux start you can change language in general param.

For 2)
Do you have gksu/gksudo package (or kdesudo/kdesu if you DE is KDE) ?
Nvidiux fail ask you your administrator password for configure nvidia-driver

**Comment by RunGp** [comment]
Retry with 1.3 release
I fix two bugs related to default language

**Comment by andrewschott** [comment]
Thanks, I have been busy since I last posted.  I did have a quick chance to take a look at things.  I was able to use x2go to get into my server, and your gut feeling may have some merit.  On EL7 the proper command is gksu-polkit.  When trying to run nvidiux I got a new (so, a third?) error, but only that one.  I presume it has to do with something that is most certainly an issue on that system, coolbits not being set.

I will work on seeing what work is involved in also porting gksu, or just creating a package that creates a symlink to gksu-polkit.

And thanks on fixing the language bug so fast!  I will continue work on the package when I have some more spare time, but work on 1.3.0 going forward.

Thanks again!  I will let you know when my package is completed and what I would call stable.

**Comment by andrewschott** [comment]
Ok, I have rebuilt the rpm, and it looks like for simplicity I will indeed have to update it with a symlink.

If I manually start things with the "gksu-polkit nvidiux" I will get a French dialogue referencing a "4", presuming this is error code 4 of some sort.  And I am not seeing anywhere where there is a file for the configuration getting generated as of yet.  Is there a way to force this so I can get the language set correctly?

Error dialogue:
![screenshot from 2016-03-19 12-38-49](https://cloud.githubusercontent.com/assets/14102747/13900251/b6a8ae2a-edcf-11e5-8495-72161fef8ef7.png)

**Comment by RunGp** [comment]
Hi

Yes nvidiux return error 4 that mean nvidiux cannot detect your nvidia  gpu

Give me the return of command

lspci -vnn | egrep 'VGA|3D'
lspci -vnn

For english language give me return of
locale

**Comment by andrewschott** [comment]
sure thing!  Thanks for the prompt aid, almost as easy as Red Hat support :)  In short I have a 560ti from a number of years ago (think its 5 yro now).

lspci -vnn | egrep 'VGA|3D' && lspci -vnn
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GF114 [GeForce GTX 560 Ti] [10de:1200](rev a1) (prog-if 00 [VGA controller])
00:00.0 Host bridge [0600]: Intel Corporation 4th Gen Core Processor DRAM Controller [8086:0c00](rev 06)
    Subsystem: ASUSTeK Computer Inc. Device [1043:8534]
    Flags: bus master, fast devsel, latency 0
    Capabilities: <access denied>
    Kernel driver in use: hsw_uncore

00:01.0 PCI bridge [0604]: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller [8086:0c01](rev 06) (prog-if 00 [Normal decode])
    Flags: bus master, fast devsel, latency 0
    Bus: primary=00, secondary=01, subordinate=01, sec-latency=0
    I/O behind bridge: 0000e000-0000efff
    Memory behind bridge: dc000000-de0fffff
    Prefetchable memory behind bridge: 00000000d0000000-00000000dbffffff
    Capabilities: <access denied>
    Kernel driver in use: pcieport

00:01.1 PCI bridge [0604]: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x8 Controller [8086:0c05](rev 06) (prog-if 00 [Normal decode])
    Flags: bus master, fast devsel, latency 0
    Bus: primary=00, secondary=02, subordinate=02, sec-latency=0
    Memory behind bridge: de200000-de2fffff
    Capabilities: <access denied>
    Kernel driver in use: pcieport

00:14.0 USB controller [0c03]: Intel Corporation 9 Series Chipset Family USB xHCI Controller [8086:8cb1](prog-if 30 [XHCI])
    Subsystem: ASUSTeK Computer Inc. Device [1043:8534]
    Flags: bus master, medium devsel, latency 0, IRQ 27
    Memory at de320000 (64-bit, non-prefetchable) [size=64K]
    Capabilities: <access denied>
    Kernel driver in use: xhci_hcd

00:16.0 Communication controller [0780]: Intel Corporation 9 Series Chipset Family ME Interface #1 [8086:8cba]
    Subsystem: ASUSTeK Computer Inc. Device [1043:8534]
    Flags: bus master, fast devsel, latency 0, IRQ 31
    Memory at de33a000 (64-bit, non-prefetchable) [size=16]
    Capabilities: <access denied>
    Kernel driver in use: mei_me

00:19.0 Ethernet controller [0200]: Intel Corporation Ethernet Connection (2) I218-V [8086:15a1]
    Subsystem: ASUSTeK Computer Inc. Device [1043:85c4]
    Flags: bus master, fast devsel, latency 0, IRQ 28
    Memory at de300000 (32-bit, non-prefetchable) [size=128K]
    Memory at de338000 (32-bit, non-prefetchable) [size=4K]
    I/O ports at f040 [size=32]
    Capabilities: <access denied>
    Kernel driver in use: e1000e

00:1a.0 USB controller [0c03]: Intel Corporation 9 Series Chipset Family USB EHCI Controller #2 [8086:8cad](prog-if 20 [EHCI])
    Subsystem: ASUSTeK Computer Inc. Device [1043:8534]
    Flags: bus master, medium devsel, latency 0, IRQ 16
    Memory at de337000 (32-bit, non-prefetchable) [size=1K]
    Capabilities: <access denied>
    Kernel driver in use: ehci-pci

00:1b.0 Audio device [0403]: Intel Corporation 9 Series Chipset Family HD Audio Controller [8086:8ca0]
    Subsystem: ASUSTeK Computer Inc. Device [1043:860b]
    Flags: bus master, fast devsel, latency 0, IRQ 33
    Memory at de330000 (64-bit, non-prefetchable) [size=16K]
    Capabilities: <access denied>
    Kernel driver in use: snd_hda_intel

00:1c.0 PCI bridge [0604]: Intel Corporation 9 Series Chipset Family PCI Express Root Port 1 [8086:8c90](rev d0) (prog-if 00 [Normal decode])
    Flags: bus master, fast devsel, latency 0
    Bus: primary=00, secondary=03, subordinate=03, sec-latency=0
    Capabilities: <access denied>
    Kernel driver in use: pcieport

00:1c.3 PCI bridge [0604]: Intel Corporation 82801 PCI Bridge [8086:244e](rev d0) (prog-if 01 [Subtractive decode])
    Flags: bus master, fast devsel, latency 0
    Bus: primary=00, secondary=04, subordinate=05, sec-latency=0
    Capabilities: <access denied>

00:1c.6 PCI bridge [0604]: Intel Corporation 9 Series Chipset Family PCI Express Root Port 7 [8086:8c9c](rev d0) (prog-if 00 [Normal decode])
    Flags: bus master, fast devsel, latency 0
    Bus: primary=00, secondary=06, subordinate=06, sec-latency=0
    I/O behind bridge: 0000d000-0000dfff
    Memory behind bridge: de100000-de1fffff
    Capabilities: <access denied>
    Kernel driver in use: pcieport

00:1d.0 USB controller [0c03]: Intel Corporation 9 Series Chipset Family USB EHCI Controller #1 [8086:8ca6](prog-if 20 [EHCI])
    Subsystem: ASUSTeK Computer Inc. Device [1043:8534]
    Flags: bus master, medium devsel, latency 0, IRQ 23
    Memory at de336000 (32-bit, non-prefetchable) [size=1K]
    Capabilities: <access denied>
    Kernel driver in use: ehci-pci

00:1f.0 ISA bridge [0601]: Intel Corporation 9 Series Chipset Family Z97 LPC Controller [8086:8cc4]
    Subsystem: ASUSTeK Computer Inc. Device [1043:8534]
    Flags: bus master, medium devsel, latency 0
    Capabilities: <access denied>

00:1f.2 SATA controller [0106]: Intel Corporation 9 Series Chipset Family SATA Controller [AHCI Mode] [8086:8c82](prog-if 01 [AHCI 1.0])
    Subsystem: ASUSTeK Computer Inc. Device [1043:8534]
    Flags: bus master, 66MHz, medium devsel, latency 0, IRQ 29
    I/O ports at f090 [size=8]
    I/O ports at f080 [size=4]
    I/O ports at f070 [size=8]
    I/O ports at f060 [size=4]
    I/O ports at f020 [size=32]
    Memory at de335000 (32-bit, non-prefetchable) [size=2K]
    Capabilities: <access denied>
    Kernel driver in use: ahci

00:1f.3 SMBus [0c05]: Intel Corporation 9 Series Chipset Family SMBus Controller [8086:8ca2]
    Subsystem: ASUSTeK Computer Inc. Device [1043:8534]
    Flags: medium devsel, IRQ 6
    Memory at de334000 (64-bit, non-prefetchable) [size=256]
    I/O ports at f000 [size=32]

01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GF114 [GeForce GTX 560 Ti] [10de:1200](rev a1) (prog-if 00 [VGA controller])
    Flags: bus master, fast devsel, latency 0, IRQ 34
    Memory at dc000000 (32-bit, non-prefetchable) [size=32M]
    Memory at d0000000 (64-bit, prefetchable) [size=128M]
    Memory at d8000000 (64-bit, prefetchable) [size=64M]
    I/O ports at e000 [size=128]
    [virtual] Expansion ROM at de000000 [disabled] [size=512K]
    Capabilities: <access denied>
    Kernel driver in use: nvidia

01:00.1 Audio device [0403]: NVIDIA Corporation GF114 HDMI Audio Controller [10de:0e0c](rev a1)
    Flags: bus master, fast devsel, latency 0, IRQ 17
    Memory at de080000 (32-bit, non-prefetchable) [size=16K]
    Capabilities: <access denied>
    Kernel driver in use: snd_hda_intel

02:00.0 Network controller [0280]: Intel Corporation Wireless 7260 [8086:08b1](rev 73)
    Subsystem: Intel Corporation Dual Band Wireless-AC 7260 [8086:4070]
    Flags: bus master, fast devsel, latency 0, IRQ 32
    Memory at de200000 (64-bit, non-prefetchable) [size=8K]
    Capabilities: <access denied>
    Kernel driver in use: iwlwifi

04:00.0 PCI bridge [0604]: ASMedia Technology Inc. ASM1083/1085 PCIe to PCI Bridge [1b21:1080](rev 04) (prog-if 01 [Subtractive decode])
    Flags: bus master, fast devsel, latency 0
    Bus: primary=04, secondary=05, subordinate=05, sec-latency=32
    Capabilities: <access denied>

06:00.0 SATA controller [0106]: Lite-On IT Corp. / Plextor M6e PCI Express SSD [Marvell 88SS9183] [1c28:0122](rev 14) (prog-if 01 [AHCI 1.0])
    Subsystem: Marvell Technology Group Ltd. Device [1b4b:9183]
    Flags: bus master, fast devsel, latency 0, IRQ 30
    I/O ports at d050 [size=8]
    I/O ports at d040 [size=4]
    I/O ports at d030 [size=8]
    I/O ports at d020 [size=4]
    I/O ports at d000 [size=32]
    Memory at de120000 (32-bit, non-prefetchable) [size=512]
    Expansion ROM at de100000 [disabled] [size=128K]
    Capabilities: <access denied>
    Kernel driver in use: ahci

 andrew  ~  Desktop 

**Comment by RunGp** [comment]
ok thanks
I work for fix tomorrow

For language detection give me also return of command
locale

**Comment by andrewschott** [comment]
#locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC=en_US.utf8
LC_TIME=en_US.utf8
LC_COLLATE="en_US.utf8"
LC_MONETARY=en_US.utf8
LC_MESSAGES="en_US.utf8"
LC_PAPER=en_US.utf8
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT=en_US.utf8
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=

**Comment by RunGp** [comment]
ok thanks
Retry with this version 
[nvidiux.tar.gz](https://github.com/RunGp/Nvidiux/files/187590/nvidiux.tar.gz)

**Comment by andrewschott** [comment]
OK, thanks.  Got a bit further.  I do run into one roadblock that may be due to the gksu implementation I have, but I can get an Xorg error upon just launching the binary, then a wrong password error code 7.

>  andrew  ~  nvidiux
> Detect lang
> Using:en_EN
> Return error?:
> Select gpu:01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GF114 [GeForce GTX 560 Ti] [10de:1200](rev a1) (prog-if 00 [VGA controller])
> 
> Nb Gpu:1
>  andrew  ~  

Lanching with gksu directly grants me with the administrator password dialogue, then it errors out in French "Gpu Nvidia introvable.  Error code:4"

>  andrew  ~  rpmbuild  SPECS  gksu nvidiux
> Detect lang
> Using:en_EN
> Return error?:/bin/sh: lspci: command not found
> 
> Select gpu:
> Nb Gpu:0

Thanks for working thru this with me, I can see why development can be a royal pain on Linux sometimes, little nagging details that are distro specific can be quite the struggle.

I did look into porting the gksu binary but it looks like with GNOME3 it was abandoned and the implementations for RHEL/Fedora seem to be quite dependent on GTK2 stuff.  Mock had a royal fit when doing my initial few specs on the source and doing a rebuild on a RHEL5 srpm was a nightmare to get nowhere.  However that said, if that would be the "magic" fix for alot of the woes, I will push forth and get a modern gksu package built.  I think there may be a way to do it.  My current implementation is just a symlink to gksu-polkit if the gksu binary is not present, and upon removal the package will remove any symlink created.

I noticed that the GNOME guys are probably the ones pushing this most of all:
[(https://wiki.gnome.org/action/show/Apps/Attic/gksu?action=show&redirect=gksu)]

If you scroll down that page a bit, there is a part about environment variable passing, perhaps I need something in there?  What env variables are you using?  I would like to add them and see if things work out better.

Thanks again,
Andrew.

**Comment by RunGp** [comment]
hello
sorry for not respond before i'm very busy in the end/beginning of month
i use only two specific env variable $DISPLAY and $HOME

No need to launch nvidiux at root 
normaly for specific function  asks root perm nvidiux use gksu
I will try use gksu-poltkit if i detect RHEL5
I'm working on this feature next week

**Comment by andrewschott** [comment]
Thats fine, I have been busy as well.

Thanks for the variables.  I will see how that can be better integrated with the RH/Fedora way.

As for su'ing -- perhaps a detection to see if gksu-polkit is present may be the better approach.  As I am not sure what distros actually have gksu/kdesu present anymore, that may be a better tactic overall since the GNOME folks have been apparently looking to push people to use this method for some time now.

Lastly, I have actually been working on packaging this for EL7, not 5.  I am not saying it cannot be done, just that packaging on EL5 is a pain compared to EL6 or EL7.

Thanks again!

**Comment by RunGp** [comment]
hello

Retry with 1.3.1 version

**Comment by andrewschott** [comment]
OK, working today on the package some more.

Everything seems good except the detection of the coolbits portion.

The english dialogue box looks great.
It does add the coolbits portion correctly ( I think, still need to look into that part)
The sudo routine works perfect.

I will post back anything that needs fixing that I can find.  I just want to ensure that its not my system thats misbehaving as I have two other EL7 systems (Both RHEL 7 Desktops) with nvidia gpus that are relatively pristine, one quite literally just got reinstalled due to a new SSD that I slapped in.

I will say, gut feeling is this is an SELinux issue on my end.

**Comment by andrewschott** [comment]
OK I am not sure how to finish troubleshooting this down, but the Coolbits entry nvidiux creates is correct.

However, I keep getting the following dialogue:
![screenshot from 2016-05-14 12-07-20](https://cloud.githubusercontent.com/assets/14102747/15269677/7f5a4766-19cc-11e6-8e28-218f78c6faf5.png)

Needless to say, I did indeed reboot, and this issue does not go away.  What things would cause this?

**Comment by RunGp** [comment]
Hi
Your /tmp directory is not remove at shutdown/reboot ?
try rm /tmp/.reboot_nvidiux

**Comment by andrewschott** [comment]
That was it!  The package apparently works.  Let me recheck everything and I will upload it to my repo and paste a link.

Thanks for all the help!  And I will look into why /tmp is NOT cleaning itself up on shutdown.

**Comment by andrewschott** [comment]
Files are up.  Application works great.

http://schotty.com/yum/el/7/repoview/nvidiux.html

**Comment by RunGp** [comment]
Good i had your package in release :)
for future release I warn you by email/other method or you follow the github?

**Comment by andrewschott** [comment]
However you feel like it.  I already have a routine weekly to check the major packages that I do and see if there are any updates.

If you wish to email (andrew at schotty.com) me thats fine, message me here is ok.  I am also on Google+ as [+AndrewSchott](https://plus.google.com/+AndrewSchott/posts).  I am [@schotty](https://twitter.com/schotty) on twitter.  Whatever works for you.  Once I get around to it, I would like to do everything via RSS, but thats another project for another time.  Still need to build a build server to automate things better.
