### ISSUE TITLE
Deleting git tags is breaking AUR package

### ISSUE THREAD

**Issue by MattSturgeon** [RunGp/Nvidiux#12]
When Nvidiux's version is updated (e.g. from 1.3 to 1.3.1) for some reason the old tag is removed.

In general it is probably bad practice to remove old version tags but in this particular case it means that the Arch package fails to install with a 404 error.

Hopefully the package will be updated soon, but in future perhaps you can leave old tags in place.

If you are concerned about out of date packages, perhaps email the various maintainers when you bump the version :)

(Sorry that this sounds like a moan!)

**Comment by RunGp** [comment]
Hello
Ok for future release i leave the old tag or i try update the aur package immediately ( I am the maintainers of ppa,deb and aur package)

Aur package is now up to date

**Comment by MattSturgeon** [comment]
Great stuff! Leaving the old version tags in will eventually build up a nice history
