### ISSUE TITLE
EL7 Package Updated 

### ISSUE THREAD

**Issue by andrewschott** [RunGp/Nvidiux#16]
http://schotty.com/yum/el/7/repoview/nvidiux.html

I also have on my repo all the deps (main dep : http://schotty.com/yum/el/7/repoview/python2-pyqtgraph.html) for your experimental monitor, although I am having issues getting it to work.

I get alot of this spammed to the terminal when launched there:

> IndexError: list index out of range
> Traceback (most recent call last):
> File "/usr/share/nvidiux/monitor/monitor2.py", line 372, in updatePlot
>  self.tabGpu[0].dataBufferGpu.append(self.getDataGpu())
> File "/usr/share/nvidiux/monitor/monitor2.py", line 279, in getDataGpu
>  self.tabGpu[0].percentGpu = int(out.split('=')[1].split(',')[0])

If you have my repo enabled, a " yum install nvidiux python2-pyqtgraph" will do the trick.  Otherwise update, and install python2-pyqtgraph.  python2-numpy python2-pyopengl python2-pyopengl-tk are the others that are needed as dependencies.  As for now, I left the explicit requirement out, since this is still flagged as experimental.  But the packages are there and ready for whenever the code is ready.

**Comment by RunGp** [comment]
hi 
Perfect continues like this. Thanks for new package.
New monitor is not ready for production.

For this bug give me return of

`nvidia-settings --query [gpu:0]/GPUUtilization`

**Comment by andrewschott** [comment]
Running it gets me different results for the graphics and memory values.  Not sure if it is supposed to or not, but here is my terminal output of several successive runs:

```
 andrew  ~  nvidia-settings --query [gpu:0]/GPUUtilization

  Attribute 'GPUUtilization' (big-red-wireless.schotty.com:0[gpu:0]): graphics=4, memory=7, video=0, PCIe=0

 andrew  ~  nvidia-settings --query [gpu:0]/GPUUtilization

  Attribute 'GPUUtilization' (big-red-wireless.schotty.com:0[gpu:0]): graphics=2, memory=5, video=0, PCIe=0

 andrew  ~  nvidia-settings --query [gpu:0]/GPUUtilization

  Attribute 'GPUUtilization' (big-red-wireless.schotty.com:0[gpu:0]): graphics=0, memory=4, video=0, PCIe=0

 andrew  ~  nvidia-settings --query [gpu:0]/GPUUtilization

  Attribute 'GPUUtilization' (big-red-wireless.schotty.com:0[gpu:0]): graphics=0, memory=4, video=0, PCIe=0

 andrew  ~  nvidia-settings --query [gpu:0]/GPUUtilization

  Attribute 'GPUUtilization' (big-red-wireless.schotty.com:0[gpu:0]): graphics=2, memory=5, video=0, PCIe=0

 andrew  ~  nvidia-settings --query [gpu:0]/GPUUtilization

  Attribute 'GPUUtilization' (big-red-wireless.schotty.com:0[gpu:0]): graphics=1, memory=4, video=0, PCIe=0

 andrew  ~  nvidia-settings --query [gpu:0]/GPUUtilization

  Attribute 'GPUUtilization' (big-red-wireless.schotty.com:0[gpu:0]): graphics=0, memory=4, video=0, PCIe=0

 andrew  ~  
```

**Comment by RunGp** [comment]
Your different results are normal.
This command return current graphic -video engine - pcie - and memory  use in percent.

But it's still a problem there is no "anomaly" with this result. I don't understand why nvidiux crash here...
I make some test with your result in python command line interpret and no crash :(
First line of return is blank ? or github had a line for readability ?

Another test 
`nvidia-settings --query [gpu:0]/GPUUtilization | head 1`

**Comment by RunGp** [comment]
This test returns nothing ? ;)

**Comment by andrewschott** [comment]
Sorry been very busy this last week.  I should have time when I get off work to run the test for you.

**Comment by andrewschott** [comment]
Indeed there is an empty line in there:

> [root@big-red-wireless andrew]# nvidia-settings --query [gpu:0]/GPUUtilization | head -n1
> 
> [root@big-red-wireless andrew]# nvidia-settings --query [gpu:0]/GPUUtilization
> 
>   Attribute 'GPUUtilization' (big-red-wireless.schotty.com:0[gpu:0]):
>   graphics=0, memory=4, video=0, PCIe=0
> 
> [root@big-red-wireless andrew]#

**Comment by RunGp** [comment]
Hi
Ok Fix Released :)
