### ISSUE TITLE
Initialization error.

### ISSUE THREAD

**Issue by Melet** [RunGp/Nvidiux#18]
Hi, when I try to run nvidiux (version:1.4.1.21). I get this error:

Traceback (most recent call last):
  File "/usr/share/nvidiux/nvidiux.py", line 1614, in <module>
    nvidiuxApp = NvidiuxApp(sys.argv[1:])
  File "/usr/share/nvidiux/nvidiux.py", line 278, in **init**
    self.createWidgets()
  File "/usr/share/nvidiux/nvidiux.py", line 401, in createWidgets
    self.initialiseData()
  File "/usr/share/nvidiux/nvidiux.py", line 648, in initialiseData
    self.piloteVersion = float(out.split(':')[-1][1:])
ValueError: invalid literal for float(): 367.36.02

I installed Nvidiux from AUR repository on Manajro 16.08 and kernel 4.7.7-0.
I also enabled coolbits in xorg, so I can change clock values manually, but Nvidiux still doesn`t work.

**Comment by RunGp** [comment]
Hello
Same issue #17 
Manjaro use a beta driver 367.36.02 and convert this to float value crash this program.

I already fix this for next minor version (1.4.2) and release is planned for next week 
It only remains to wait

**Comment by Melet** [comment]
Thank you for answer, I didn`t see this closed issues button. I appreciate quick response and effort for maintaining this program.
Best regards.
