### ISSUE TITLE
nvidia 560 M

### ISSUE THREAD

**Issue by raulken78** [RunGp/Nvidiux#19]
Hi friend, I have a double 560 M installed on my alyenware dell.
I am the unique people in the world use it under linux ubuntu with 2 monitor, with a little tips :-)
This graphicard cant setup freq, cant setup fun, cant setup anyparam but I found this solution:
if my graphycs card go to 95C and I put my notebook on suspension just for some second, and put ON all CPU run to min and all GPU go to performance level 1 and dnot move from here.

Are U idea of reply this dnot move from performance level 1 whitout my tips?

If U want other info please reply here, ty

**Comment by RunGp** [comment]
hi
How I have absolutely no idea why your tips force gpu go to performance level 1
Try desactivate/activate checkbox maxperformance with nvidiux and see the result
if this fail i can't help you
