### ISSUE TITLE
App doesn't start

### ISSUE THREAD

**Issue by ghtux** [RunGp/Nvidiux#2]
Get following error when starting with nvidiux:

Traceback (most recent call last):
  File "/usr/share/nvidiux/nvidiux.py", line 1342, in <module>
    nvidiuxApp = NvidiuxApp(sys.argv)
  File "/usr/share/nvidiux/nvidiux.py", line 202, in **init**
    self.createWidgets()
  File "/usr/share/nvidiux/nvidiux.py", line 296, in createWidgets
    self.initialiseData()
  File "/usr/share/nvidiux/nvidiux.py", line 468, in initialiseData
    compatibility = self.iscompatible()
  File "/usr/share/nvidiux/nvidiux.py", line 447, in iscompatible
    self.showError(-1,_translate("Configuration",None),_translate("La configuration du fichier xorg n'est pas effectue !\n Entrer votre mot de passe administrateur pour effectuer la configuration",None),self.info)
TypeError: _translate() takes exactly 3 arguments (2 given)

It's a Gtx 970 @ linux mint 17.3, driver is 361.189

---

Solved by setting "coolbits" in Xorg.conf.

New error:

Traceback (most recent call last):
  File "/usr/share/nvidiux/nvidiux.py", line 1346, in <module>
    nvidiuxTranslator.load("qt_" + locale,QtCore.QLibraryInfo.location(QtCore.QLibraryInfo.TranslationsPath))
NameError: name 'locale' is not defined

**Comment by RunGp** [comment]
hello 
thanks for reporting bug.
Fix is released
I upload a new deb (1.1) with fix
try and tell me if it works

for use all nvidiux functionality add
Option         "Coolbits" "28" in file xorg.conf

**Comment by ghtux** [comment]
Installed the deb 1.1 package and app is starting!

But the startup script for auto loading overclocking isn't working:
./startup.sh: line 11: Syntax error word »fi«
./startup.sh: line 11: `    fi'

Is it possible to run my gtx970xxx.ndi profile from command line option with nvidiux? 

Tried nvidiux ~/user/gtx.ndi from command line and it's working. But I don't want to see the app itself. A quiet startup loading would be nice :-)

And btw: if you need help with translating to english or german just let me know and I'll help you

**Comment by RunGp** [comment]
Ok i search the problem with startup script
For quiet startup loading no problem i add this in my todo list (wait nvidiux 1.2)
Of course I accept help for german translation.

**Comment by ghtux** [comment]
Translated the nvidiux_en_EN.ts into german. nvidiux doesn't use the new translation values. If you tell me how I could test it.

**Comment by RunGp** [comment]
You must generate the new langfile with the translated nvidiux_en_EN.ts and add it for german langage
The simplest way is send me  the translated file nvidiux_en_EN.ts in german by mail

**Comment by ghtux** [comment]
[nvidiux_de_DE.ts.zip](https://github.com/RunGp/Nvidiux/files/102432/nvidiux_de_DE.ts.zip)

**Comment by RunGp** [comment]
Yep
For startup script i found the bug i released fix soon
I have also had german language but it lacks one sentence
Traduce this in german for me : "The author and community are not responsible of bad use and no liability for damages, direct or consequential, which may result from the use of Nvidiux.\nNvidiux is in no way affiliated to Nvidia."
Quiet startup loading is done.
With nvidiux 1.2 use -s or --silent <ndiprofile> and nvidiux will not show interface-

**Comment by ghtux** [comment]
Looking forward to V 1.2, you didn't upload it already, did you?

This one sentence is hard to translate:

Weder der Autor noch die beteiligte Gemeinschaft haften bei falscher Benutzung. Jedweder Schadenersatzanspruch bei direkter oder daraus erfolgter Nutzung von Nvidiux ist ausgeschlossen. 
Nvidiux steht in keiner Verbindung mit der NVIDIA GmbH.

**Comment by RunGp** [comment]
I upload V1.2 soon (probably tomorrow)
German trad is now complete :)

**Comment by ghtux** [comment]
Translated it again. This one is much better :-)

Der Autor und die beteiligte Gemeinschaft sind nicht verantwortlich bei unsachgemäßer Verwendung und übernehmen keinerlei Haftung für Schäden, direkt oder indirekt, die sich aus der Verwendung von Nvidiux ergeben könnten. Nvidiux steht in keiner Verbindung mit der NVIDIA GmbH.

**Comment by RunGp** [comment]
Version 1.2 released

**Comment by ghtux** [comment]
Everything working so far. The startup script seems to work too, haven't restarted yet :dancer: 

Nice work man!

**Comment by RunGp** [comment]
Nice :-)
I had your nvidia card in white list (Gtx 970)
For future release can i send you all new sentence for german translation ?

**Comment by ghtux** [comment]
It's still not white listed. It's an Asus gtx970 Strix and nvidiux tells me it's not white listed. 
Gpu and shader core are not correkt though, it says 1455 mhz but it should be 1355. Doesn't matter while overclocking is working. 

A few entrys are not translated or take too much space in german :-) 

Sure, send me the sentences, will gladly help you translating and testing.

Could you think about adding direct value editing to raise frequencies? The slider is a bit difficult sometimes in order to get the right frequencies :D

**Comment by RunGp** [comment]
No direct value editing is worse for security and maintenance
For Gpu and shader core i use value found by nvidia driver but in some case value is more high than official because of nvidia gpu boost tech (2.0 for your card)

**Comment by RunGp** [comment]
Send me your email
I close this thread soon

**Comment by ghtux** [comment]
New to git, where can I send mails to someone?

**Comment by RunGp** [comment]
hum good question i don't know ^^

**Comment by ghtux** [comment]
mglinux@cryptolab.net

Public mail used for GitHub now. So you and anyone else can send me mails. Now you could close this issue :-)
