### ISSUE TITLE
NVIDIA GeForce GTX 750 Ti

### ISSUE THREAD

**Issue by tenten8401** [RunGp/Nvidiux#21]
The GeForce GTX 750 Ti is a compatable card, however:
Running the latest drivers on linux and am experiencing an issue where the clock speed offset is 293Mhz above what it actually is. (1000)

For instance, if I set gpu clock speed to 1400Mhz, Powermizer claims it's only at 107Mhz above minimum

![image](https://cloud.githubusercontent.com/assets/6174343/18105039/f270903a-6ecb-11e6-8cf4-b97690ab893c.png)

**Comment by RunGp** [comment]
HI
yes nvidia driver can change for your exemple frequency between this range [135 min - 1409 max] according to gpu load and temperature.
What wrong with this ?

**Comment by tenten8401** [comment]
Just now realized my benchmark program didn't like it. Also, could you add the 750Ti to the whitelist?
