### ISSUE TITLE
Apply on restart has no effect

### ISSUE THREAD

**Issue by tenten8401** [RunGp/Nvidiux#22]
"Apply on restart" has no effect running Kubuntu 16.04.1 LTS x64 running NVIDIA driver version 361.42. Please have a look at this.

**Comment by RunGp** [comment]
Hi
Restart system use cron deamon 
Cron deamon are active on your system ?

Give me return of command 

sudo crontab -l
sudo -u $USER nvidiux -s /home/$USER/.nvidiux/StartupSys.ndi

after second command verify if the overclock fail or not

**Comment by tenten8401** [comment]
Probably needed to get the daemon up
