### ISSUE TITLE
Updated EL7 packge to 1.4.3

### ISSUE THREAD

**Issue by andrewschott** [RunGp/Nvidiux#24]
Updated EL7 package to 1.4.3.

My repo release file:
http://schotty.com/yum/el/7/repoview/schotty-el7-release.html

nvidiux packages:
http://schotty.com/yum/el/7/repoview/nvidiux.html

To install:
From terminal issue:
yum install nvidiux

**Comment by RunGp** [comment]
Hi
Thanks
Package updated
