### ISSUE TITLE
Geforce 8400 GS Rev. 2

### ISSUE THREAD

**Issue by Arzte** [RunGp/Nvidiux#25]
This card seems to be semi-compatible, while reading the current GPU, shader, and memory clocks are correct on startup, and overclocks while saying it was successful, never get applied. Also while my cards clock can reach 745Mhz I'm limited to 737 by the slider bar (though this is a minor complaint)

**Comment by RunGp** [comment]
hi

overclock with nvidiux only work for nvidia gpu generation 4XX or newer

**Comment by Arzte** [comment]
That's too bad, really awesome application, guess I have to use nvidia's overclocking non-sense.
