### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by LeCharlatan** [RunGp/Nvidiux#28]
Hi,

I've got an error at launch. My GPU is Nvidia GTX 1070.
If you need more informations, ask me :)

Here the link for picture
[https://ibb.co/jpKB0k](url)

Thanks

**Comment by herbert56** [comment]
Hi,
I think I have the same issue with error 4. I got a GTX 1080 and i need a tool to set the voltage to a target. So please help us, because there is now alternative on linux, yet.

Thanks for helping us.

**Comment by prestonLibby** [comment]
Hello, I believe I too have this problem. It's saying the GTX 1070 is not in the whitelisted gpus:
https://imgur.com/H9kVOtd

An update to include the latest 10-series GPUs would be amazing.

EDIT: So I found where the whitelist exist in nvidiux.py, which just has a small typo regarding uppercase vs. lowercase. However, once I fix that issue I'm getting a new set of traceback errors:

`Traceback (most recent call last):
  File "/usr/share/nvidiux/nvidiux.py", line 1608, in <module>
    nvidiuxApp = NvidiuxApp(sys.argv[1:])
  File "/usr/share/nvidiux/nvidiux.py", line 284, in __init__
    self.createWidgets()
  File "/usr/share/nvidiux/nvidiux.py", line 397, in createWidgets
    self.initialiseData()
  File "/usr/share/nvidiux/nvidiux.py", line 882, in initialiseData
    if self.tabGpu[i].arch == "pascal" and self.driverVersion < 370.01:
AttributeError: 'NvidiuxApp' object has no attribute 'driverVersion'`

Will continue to dig, as it's crazy that despite how fast Linux gaming has been growing in recent months, we still have few to no methods of overclocking, benchmarking, etc. for gaming.

**Comment by RunGp** [comment]
Hi
Bugfix is released

**Comment by LeCharlatan** [comment]
Thanks @RunGp !
