### ISSUE TITLE
Startup script not working

### ISSUE THREAD

**Issue by ghtux** [RunGp/Nvidiux#3]
Hi again!

The Startup script isn't working, tried several times. 

Now a good option is the silent start of nvidiux. I run nvidiux -s /home/user/gtx970oc.ndi

Output: Erreur Chargement configuration; error code 20
Pressing OK the "this gpu is not in the white list" nag appears. Pressing OK again.

It applys the overclock profile! So the error is strange and annoying. Also the nag screen with ... not in white list. Could you look what's causing the error 20 and disable the white list notification? Or tell me how to add my gtx to white list.

Thx again for this great tool!

**Comment by RunGp** [comment]
Hi

Error 20 is normaly a corupt configuration file i need mode information for debug this
try with this deb 
Change :
Add your card are in white list 
Nvidiux will be crash and give better error message 
[nvidiux.zip](https://github.com/RunGp/Nvidiux/files/108528/nvidiux.zip)

**Comment by ghtux** [comment]
lspci -vnn | egrep 'VGA|3D' doesn't work it seems.  Output for lspci:

02:00.0 VGA compatible controller [0300]: NVIDIA Corporation GM204 [GeForce GTX 970] [10de:13c2](rev a1) (prog-if 00 [VGA controller])
    Subsystem: ASUSTeK Computer Inc. Device [1043:8508]
    Flags: bus master, fast devsel, latency 0, IRQ 35
    Memory at f5000000 (32-bit, non-prefetchable) [size=16M]
    Memory at d0000000 (64-bit, prefetchable) [size=256M]
    Memory at e0000000 (64-bit, prefetchable) [size=32M]
    I/O ports at e000 [size=128]
    [virtual] Expansion ROM at f6000000 [disabled] [size=512K]
    Capabilities: <access denied>
    Kernel driver in use: nvidia

The Profile error (20) is gone. Created a new profile. So how can I add my gtx to whitelist?

**Comment by RunGp** [comment]
Hum popup "this gpu is not in the white list" is a bug your card is already in white list
[nvidiux.zip](https://github.com/RunGp/Nvidiux/files/108586/nvidiux.zip)
re-try with this new deb file

**Comment by ghtux** [comment]
That's it! No more popups and it's working! Thx!

Got the idea of learning python myself. We will see :D

**Comment by RunGp** [comment]
Good choice python is easy to learn :)
For startup script problem
if you use manual launch he print error message ? give me exit code $?

**Comment by ghtux** [comment]
I got no error code when launching startup.sh. It seems in a loop doing nothing. Right now I am using nvidiux -s profile.ndi with crontab to exec it at boot.

**Comment by RunGp** [comment]
yep it's a good idea
I will simplify startup script i can use this command now
@reboot nvidiux -s ~/.nvidiux/startup_system.ndi
Add to my todo list
