### ISSUE TITLE
Issue when launching

### ISSUE THREAD

**Issue by tactic123** [RunGp/Nvidiux#32]
Hi,

I tried runnin the Tool but do get Error Code -34 during startup.
I have three GTX1060 installed.
Ubuntu 16.04

Any idea how to fix?

**Comment by RunGp** [comment]
Hi 
Nvidiux can not initialise your 3 GTX1060

Give me return of 
```
lspci -vnn | grep NVIDIA | grep -v Audio | grep GeForce

nvidia-smi -L
```

**Comment by tactic123** [comment]
Hi,

After reinstalling the tool and downgrade the NVIDIA driver it’s working now.
Tjanks
