### ISSUE TITLE
Error code -34

### ISSUE THREAD

**Issue by kotik-o** [RunGp/Nvidiux#33]
Hi,

I'm using Ubuntu 17.10 with 6x GPU ASUS GTX1070. Once I open the nvidiux I get this error:

ERROR -34. GPU conf not found. 

Do you know how to fix it? Thanks.

**Comment by RunGp** [comment]
hi

6 GPU ^^ i never test nvidiux with more 2 gpu 
I have an idea for your problem but i cannot try to fix this before wednesday

**Comment by kotik-o** [comment]
Hi,
I found your program in a mining forum. A lot of people, like me, have a lot of problems to overclock the nvidia GPU under linux. (I have changed the xorg.conf manually, adding coolbits, but I only can overclock GPU 0). Seems that your program can help with our issue.
If you can solve my issue, I recommend you to promote your program in ethereum mining forums.. A LOT of users will join your program.

**Comment by RunGp** [comment]
hi 
I found a fix for your problem ( test with 3 gpu)
I will try push 1.4.6 ( or maybe 1.5 with experimental new interface) for February
