### ISSUE TITLE
"apply this profile at system startup" grayed out

### ISSUE THREAD

**Issue by logix2** [RunGp/Nvidiux#36]
The "apply this profile at system startup" (not at nvidiux startup!) option is grayed out, and I can't enable it on Ubuntu 18.10 (GeForce GTX 980). Any idea what's wrong here?

**Comment by logix2** [comment]
Oh and one more thing. ``nvidiux -s PROFILE.ndi`` doesn't work. It opens the Nvidiux GUI and displays "NO STAT" in the terminal and doesn't apply the profile. However, ``nvidiux --silent PROFILE.ndi`` does work.

**Comment by RunGp** [comment]
Hi
This is "normal" since 2.0 version of nvidiux i have disabled this functionality because this not work on most configuration. I planned release a better system for next release.
For nvidiux -s PROFILE.ndi i will take reproduce the bug and fix it.
Thanks for reporting bugs

**Comment by RunGp** [comment]
Fix ready for -s option (version 2.1)
Release soon

**Comment by Cosmatinco** [comment]
Hi guys i just installed it and its saying that my card Nvidia 1060 isnt  supported .. i am using 435 drivers and cuda 10 and there was a worning as well that this program doesnt support more the 4 GPU at once... code 52 ... cheers
