### ISSUE TITLE
Fails to modify existing xorg.conf

### ISSUE THREAD

**Issue by logix2** [RunGp/Nvidiux#37]
If an /etc/X11/xorg.conf file exists, but it doesn't have the Coolbits option, Nvidiux says it needs to change this file. After allowing it to modify the existing xorg.conf file, the file is actually not changed (is exactly as it was before).

When no xorg.conf file is present on the system, Nvidiux is able to generate the xorg.conf file and append the Coolbits option without any issues.

This happens on my Ubuntu 18.10 desktop.

**Comment by RunGp** [comment]
Hi 
Okay
I will try to reproduce this issue and fix this for next stable version.
But not now actually i doesn't have my dev computer

**Comment by xpander69** [comment]
This is also 1 good example why we wouldn't want to touch the xorg.conf file and use the /etc/X11/xorg.conf.d/ location for configurations like these.

Issue/suggestion about it here:
https://github.com/RunGp/Nvidiux/issues/38

**Comment by RunGp** [comment]
Cannot reproduce this bug 
work on ubuntu 18.04 / 18.10 / 19.04dev
Now nvidiux will use /etc/X11/xorg.conf.d
considering bug is fix.
