### ISSUE TITLE
Don't try to write everyting into xorg.conf

### ISSUE THREAD

**Issue by xpander69** [RunGp/Nvidiux#38]
People might have their own conf files and forcing to create a /etc/X11/xorg.conf file can mess up peoples multi-monitor Configurations or when changing GPUs etc.

why not use the proper /etc/X11/xorg.conf.d/ directory that stores host-specific configuration.

you should only also write the parts that are relevant for this program. Like:

```
Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    Option         "Coolbits" "28"
Endsection
```
 

https://wiki.archlinux.org/index.php/Xorg#Using_.conf_files

_You are free to add configuration files there, but they must have a .conf suffix: the files are read in ASCII order, and by convention their names start with XX- (two digits and a hyphen, so that for example 10 is read before 20). These files are parsed by the X server upon startup and are treated like part of the traditional xorg.conf configuration file. Note that on conflicting configuration, the file read last will be processed. For that reason the most generic configuration files should be ordered first by name. The configuration entries in the xorg.conf file are processed at the end._

**Comment by RunGp** [comment]
Hi
Okay if this not specifix to arch why not ?
I make some search and use this method for next stable release 2.1 if this work on all disto

**Comment by xpander69** [comment]
https://manpages.debian.org/stretch/xserver-xorg-core/xorg.conf.5.en.html

As far as i know its the default Xorg behavior. I know Ubuntu and Debian also make use of this for sure, but no idea about every distro on the planet. Though since in Xorg man pages, i guess every distro that is not by some reason modifying the behavior is using the same stuff.

By adding this programs needed Coolbits into this section wont break the user made configuration tweaks. That was my whole point.

**Comment by andrewschott** [comment]
RHEL7+ and Fedora follow suit here as well.  This is a goid feature to support.

**Comment by RunGp** [comment]
Add xorg.conf.d support
Nvidiux now create /etc/X11/xorg.conf.d/nvidiux.conf file
