### ISSUE TITLE
Gpu Nvidia introuvable Error Code:4

### ISSUE THREAD

**Issue by Dannation** [RunGp/Nvidiux#4]
Hi there, I just installed your program, and I keep getting this error code when I try to run nvidiux or sudo nvidiux. This is the error window I get: http://i.imgur.com/kCU1gks.png

I'm running Linux Mint 17.3 with the 4.3.0 kernel with 352.63 Nvidia drivers running for my G1 Gaming GTX 970.

Here is the output I get from running: lspci -vnn | grep NVIDIA | grep -v Audio

01:00.0 VGA compatible controller [0300]: NVIDIA Corporation Device [10de:13c2](rev a1) (prog-if 00 [VGA controller])

Thank you so much for making this program, it fills a void in the Linux gaming community that really isn't filled by nvidia-settings.

**Comment by RunGp** [comment]
Hi
This is strange 
Return of your lspci do not contain name of your gpu  (aka GeForce XXXXX)
If i comparing with me
02:00.0 VGA compatible controller [0300]: NVIDIA Corporation GF110 [GeForce GTX 570] [10de:1081](rev a1) (prog-if 00 [VGA controller])
Nvidiux only work with GeForce XXXXX for exclude professional card (Quadro and Tesla) and strange device with custom bios

Do you (or vendor of this card ) install custom bios or firmware on this gpu ?

**Comment by Dannation** [comment]
I haven't installed any custom bios on the card, but I did buy it used off of eBay, do you think that could be a possible cause for the strange lspci output?

**Comment by RunGp** [comment]
I don't know perhaps.
How did you install proprietary nvidia driver ? 
try with a newer version 361.XX

**Comment by xpander69** [comment]
and here is my output, just for compare:

xpander@arch ~ $ lspci -vnn | grep NVIDIA | grep -v Audio
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GM204 [GeForce GTX 970] [10de:13c2](rev a1) (prog-if 00 [VGA controller])

its Asus STRIX 970
361.18 drivers

**Comment by Dannation** [comment]
I will try the newer driver and see if that changes my output, I'll check back in later on with my results.

**Comment by RunGp** [comment]
hello 
do you try newer drivers ?

**Comment by Dannation** [comment]
Yeah, I'm now using the 361.18 Nvidia drivers, and I get the same output.

**Comment by RunGp** [comment]
hi
Install nvidia-smi 
and try with the last version (1.2.3)
I had some new test for detect more nvidia card

**Comment by ghtux** [comment]
Will try tomorrow. Could you update the PPA? This way I don't forget it
when seeing updates :-)

Am 14.02.2016 um 17:02 schrieb RunGp:

**Comment by mglinux** [comment]
1.2.3 works as before, didnt notice any difference. Working AS intented

**Comment by RunGp** [comment]
hi
yep it's normal method 1 already detect your nvidia card , for your case 
it uselless perform more check.
This fix is for exotic card (custom bios, custom driver etc...) than not 
show their name with lspci command.
I wait reponse of @Dannation
**

**Comment by Dannation** [comment]
Ok, will try the latest version later today, will update after that.

**Comment by RunGp** [comment]
hello
No response the last version works ?
