### ISSUE TITLE
Unable to build on arch (aur package)

### ISSUE THREAD

**Issue by ghost** [RunGp/Nvidiux#46]
error using the aur package.
kernel 4.20.11:

/.cache/pikaur/build/pyqt4/src/PyQt4_gpl_x11-4.12.3/QtCore/sipQtCoreQAbstractTransition.cpp:812:1: error: cannot convert ‘std::nullptr_t’ to ‘int’ in initialization
 
 ^
make[1]: *** [Makefile:689: sipQtCoreQAbstractTransition.o] Error 1
make[1]: Leaving directory '/home/.cache/pikaur/build/pyqt4/src/PyQt4_gpl_x11-4.12.3/QtCore'
make: *** [Makefile:60: sub-QtCore-make_default-ordered] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

Command 'makepkg --force' failed to execute.

**Comment by RunGp** [comment]
Hi

This section of code doesn't concern nvidiux.
seam build of pyqt4sip failed.
try install ( or reinstall) python2-sip-pyqt4

**Comment by ghost** [comment]
Thanks, already have it installed,  Must have a broken or corrupted package somewhere. I'll close this since not nvidux issue.
