### ISSUE TITLE
Confirm GTX 650 TI is working and can be added to whitelist.

### ISSUE THREAD

**Issue by krassswr** [RunGp/Nvidiux#49]
Hello, I'm using video card GTX 650 TI, and I can confirm that coolbits are activated successfully and overclocking is working on this card. 
Nvidiux 2.2
Nvidia binary driver 418.74, OS Debian 10 testing.
02:00.0 VGA compatible controller: NVIDIA Corporation GK106 [GeForce GTX 650 Ti] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: ASUSTeK Computer Inc. GK106 [GeForce GTX 650 Ti]
	Flags: bus master, fast devsel, latency 0, IRQ 25, NUMA node 0
	Memory at fb000000 (32-bit, non-prefetchable) [size=16M]
	Memory at d0000000 (64-bit, prefetchable) [size=128M]
	Memory at de000000 (64-bit, prefetchable) [size=32M]
	I/O ports at bc00 [size=128]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: [60] Power Management version 3
	Capabilities: [68] MSI: Enable+ Count=1/1 Maskable- 64bit+
	Capabilities: [78] Express Endpoint, MSI 00
	Capabilities: [b4] Vendor Specific Information: Len=14 <?>
	Capabilities: [100] Virtual Channel
	Capabilities: [128] Power Budgeting <?>
	Capabilities: [600] Vendor Specific Information: ID=0001 Rev=1 Len=024 <?>
	Kernel driver in use: nvidia
	Kernel modules: nvidia

**Comment by RunGp** [comment]
Hi
Thanks for this return
GTX 650 added to white List
