### ISSUE TITLE
Needs some tweaking for Black Themes

### ISSUE THREAD

**Issue by xpander69** [RunGp/Nvidiux#5]
https://dl.dropboxusercontent.com/u/28788188/ss_03022016_11.59.09.png

tux logo is transparent it seems :)
also the info box where you pick your GPU is not readable.

**Comment by RunGp** [comment]
hi
Yes all image use transparency on next version (1.2.1) tux will be replaced by your nvidia card

You speak about the Infobox with light blue background color ? or another ?
On your screenshoot i can read name of your gpu

**Comment by xpander69** [comment]
my GPU is not whitelisted to show the nvidia card logo :) and the issue remains for about page :)

ohh yeah screenshot has my listed gpu selected, then its readable.

when its not selected its not visible:

https://dl.dropboxusercontent.com/u/28788188/ss_03022016_12.51.23.png

**Comment by RunGp** [comment]
oki
all inactive bouton are also invisible
Solution : transparent backgound color (Fix in next minor version :) )
For (tux logo/card) no easy solution and i do not write specific code for suport all existing themes

**Comment by xpander69** [comment]
its understandable you dont write code for specific themes, cause there are many of those :)
just i think it doesnt want to agree with gtk theme colors well.. cause i dont see this issue in other programs... but ofc it might be my theming issue

**Comment by RunGp** [comment]
In other qt program background color of image do not change ?

**Comment by xpander69** [comment]
ohh its qt? ..i feel stupid now :) in that case it makes sense that it doesnt always match... its up to me to fix it then... dont bother with that :)

**Comment by RunGp** [comment]
yes it a qt4 program
No problem

**Comment by RunGp** [comment]
Version 1.2.1 released
Remove custom background color

**Comment by xpander69** [comment]
superb work and speedy update:D it fixes everything:D 

https://dl.dropboxusercontent.com/u/28788188/ss_03022016_17.49.57.png

thank you!
