### ISSUE TITLE
README.md Debian instructions

### ISSUE THREAD

**Issue by LucasGood** [RunGp/Nvidiux#50]
`Debian in command line use :

wget https://github.com/RunGp/Nvidiux/releases/download/2.0.2/nvidiux.deb
sudo dpkg -i nvidiux.deb
sudo apt-get install -f
`

results in error `Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-06-16 18:12:45 ERROR 404: Not Found.`

I have installed the .deb package successfully, the instruction just needs to be updated.

**Comment by RunGp** [comment]
Thanks 
README updated
