### ISSUE TITLE
Can't detect GTX 960

### ISSUE THREAD

**Issue by Sensu0** [RunGp/Nvidiux#55]
I run Ubuntu 19.10.

Tested this so far with nvidiux 2.1 (from git repo) and 2.0.4 (from ppa) and with drivers 440 and 435.

When I start the program I get error code 29 and then some text box in french saying "Driver non testé (support < 451.1)! Vouluez vous activer l' overclocking" asking for a yes or no answer. Either answer will get me error code 31.

This is the output I'm getting when starting it from the command-line. I have both the amd64 and i386 packages for "canberra-gtk-module". Earlier, I only had the amd64 package of it.

Gtk-Message: 12:35:46.611: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/usr/share/nvidiux/nvidiux.py", line 1869, in <module>
    nvidiuxApp = NvidiuxApp(sys.argv[1:])
  File "/usr/share/nvidiux/nvidiux.py", line 306, in __init__
    self.createWidgets()
  File "/usr/share/nvidiux/nvidiux.py", line 472, in createWidgets
    self.initialiseData()
  File "/usr/share/nvidiux/nvidiux.py", line 959, in initialiseData
    self.tabGpu[i].memInterface = int(out2.split("):")[1].split(".")[0])
IndexError: list index out of range

**Comment by zacmario** [comment]
I have the same issue with lubuntu 19.04, gtx 730

**Comment by RunGp** [comment]
nvidiux is no longer developed please une nvidia-settings if your card is not supported
