### ISSUE TITLE
in ubuntu 20.04 focal no working problems with python qt4

### ISSUE THREAD

**Issue by jomarocas** [RunGp/Nvidiux#59]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python-qt4 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-qt4' has no installation candidate

cannot install python-qt4

**Comment by MrGarrowson** [comment]
QT is currently on version 5, I think all qt4 packages have been removed on Ubuntu 20.04 official repos. It's still possible to add them with this PPA:  ppa:rock-core/qt4, however the final solution should be to move everything to qt5. Check this link for more info.
 https://askubuntu.com/questions/1234786/qt4-libqt4-in-ubuntu-20-04

**Comment by TobiasJu** [comment]
Same Problem here. I can not add older repositories to my env.

**Comment by Rampagy** [comment]
I use Fedora 33 and am having the same issues.

    Traceback (most recent call last):
      File "/usr/share/nvidiux/nvidiux.py", line 19, in <module>
        from PyQt4.QtCore import *
    ImportError: No module named PyQt4.QtCore

**Comment by RunGp** [comment]
nvidiux is no longer developed ,  i have on time to port this program to python3 and pyqt 5
