### ISSUE TITLE
MSI gtx760

### ISSUE THREAD

**Issue by Cyberpangolin** [RunGp/Nvidiux#6]
Salut!

Un immense merci pour ton programme :)

J'ai une MSI gtx-760 qui est supposée atteindre 1241 Mhz.

En lançant nvidiux, j'ai un retour visuel tout à fait correct, mais aucune différence dans la fréquence effectivement appliquée: la "graphics clock" des pilotes nvidia indique toujours 1019 Mhz, soit la fréquence d'usine et il n'y a aucun changement de performance.

Si j'en crois http://www.lesnumeriques.com/carte-graphique/msi-geforce-gtx-760-gaming-oc-p17053/test.html, sur windows il existe une "MSI Gaming App", qui, je cite:

> désactive la fonctionnalité GPU Boost et permet de bloquer la fréquence à 1215 MHz de manière constante.

Donc: est-ce possible d'intégrer dans nvidiux un moyen de passer outre ce 1019Mhz peu seyant?

L'overclock de la mémoire ne pose, lui, aucun souci particulier, et je peux voir le "memory transfer rate" en haut changer.

![capture du 2016-02-19 06 59 08](https://cloud.githubusercontent.com/assets/12512762/13167763/7d5db116-d6d6-11e5-9a83-92f863f06ea7.png)

Edit: correction du post

**Comment by RunGp** [comment]
Bonjour
Je ne croit pas que ce soit possible sur ta capture on vois bien que la frequence "base clock 3d" est à 1260Mhz. Donc niveau parametrage de la carte pour l'overclocking tous est ok.
Normalement gpu boost ou pas la frequence doit respecter cette base si on est en mode perf max (et quand la carte est en charge jeux film etc...)
Gpu boost augmente la frequence à partir de la "base clock 3d" il ne la baisse pas.
Ici c'est clairement pas le cas  donc je dirait bug ou limitation specifique effectué par msi sur cette carte.

J'ai fais une recherche rapide sur le web à priori aucun moyen de desactiver gpu boost sous linux.

Edit : si tu trouve une solution universelle par contre ça m'interese je pourrais essayer de l'integrer à Nvidiux sous forme d'option.

**Comment by Cyberpangolin** [comment]
Alors... après recherche, et divers essais, Je peux monter la fréquence de la mémoire (déjà dit), monter la fréquence maxi que le gpu devrait en principe pouvoir atteindre mais en fait non, et l'underclock (sous 1019 Mhz) est impossible. La valeur est simplement ignorée par le pilote nvidia. 
La vitesse du ventilo est librement configurable, mais il ne monte jamais à plus de 30% en mode automatique, compte tenu de la basse fréquence.

Je pense donc que tu peux flagger cette carte comme partiellement incompatible.

Bon, ben il me reste plus qu'à voir si je peux trouver une valeur directement à changer quelque part dans les tréfonds de mon système, et si j'aurais plus de chance sur le forum ubuntu-fr.
Je me dis que peut-être que si j'arrive à passer Adaptive Clocking de enabled à disabled ça peut avancer les choses...

Edit: je viens de contacter MSI, ce serait top s'ils avaient une solution :D

**Comment by Cyberpangolin** [comment]
OK, je l'ai :dancer: 
Donc, il manque, pour que ça fonctionne, ceci: 

```
Section "Device"
  Identifier "NVIDIA GeForce"
  Driver     "nvidia"
  Option     "RegistryDwords" "PowerMizerEnable=0x1; PerfLevelSrc=0x2222; PowerMizerDefaultAC=0x1"  
EndSection
```

trouvé ici: http://ubuntuforums.org/showthread.php?t=1933305

mon xorg devient donc: 

```
Section "Device"
    Option         "Coolbits" "28"
  Identifier "NVIDIA GeForce"
  Driver     "nvidia"
  Option     "RegistryDwords" "PowerMizerEnable=0x1; PerfLevelSrc=0x2222; PowerMizerDefaultAC=0x1"  
EndSection
```

Du coup, ma clock est, native, à 1200Mhz, et je peux monter vers 1350 sans crash.

Edit: Oups, y'a un décalage de 39 MHz entre la valeur indiquéee par nvidiux et le pilote ndvidia...
nvidia dit 1202 MHz, nvidiux dit 1241. Mais bon, l'important c'est déjà d'avoir pu monter un bon bout :)

**Comment by RunGp** [comment]
ok super :)
donc ce paramètre permet de desactiver Adaptive Clocking
Je mettrait une option qui permettra de le faire depuis nvidiux prochainement
