### ISSUE TITLE
Sadly not running on Mint 20

### ISSUE THREAD

**Issue by MrEnergy64** [RunGp/Nvidiux#61]
Hi,

I was looking like that kind of programm, but sadly it is not running on a MINT 20 machine:

Linux GEDU-MINT.gedu.net 5.7.1-050701-generic #202006071230 SMP Sun Jun 7 12:32:55 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

dpkg: dependency problems prevent configuration of nvidiux:
 nvidiux depends on python-qt4; however:
  Package python-qt4 is not installed.
 nvidiux depends on vainfo; however:
  Package vainfo is not installed.
 nvidiux depends on python-tk; however:
  Package python-tk is not installed.
 nvidiux depends on python-psutil; however:
  Package python-psutil is not installed.

I followed your suggestion for a Ubuntu 20 user:

sudo add-apt-repository ppa:rock-core/qt4                                                                                                            1 ⨯
You are about to add the following PPA:
 More info: https://launchpad.net/~rock-core/+archive/ubuntu/qt4
Press Enter to continue or Ctrl+C to cancel

Executing: /tmp/apt-key-gpghome.zeQDwIvqNO/gpg.1.sh --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys 63BBCC76C6D55B7DF2D65B2A78CB407D3E3D8F94
gpg: key 78CB407D3E3D8F94: public key "Launchpad PPA for Rock Core" imported
gpg: Total number processed: 1
gpg:               imported: 1

but sadly not working either:

sudo apt-get install libqtcore4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libqtcore4 : Depends: qtcore4-l10n but it is not going to be installed
 nvidiux : Depends: python-qt4 but it is not installable
           Depends: vainfo but it is not going to be installed
           Depends: python-tk but it is not going to be installed
           Depends: python-psutil but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

It would be great, when you could migrate your prog to python3.

Kindly Regards

**Comment by RunGp** [comment]
nvidiux is no longer developed , i have no time to port this program to python3 and pyqt 5
