### ISSUE TITLE
Error code: 2

### ISSUE THREAD

**Issue by D0V4HKIIN** [RunGp/Nvidiux#62]
I get this error when starting the app (as seen in the picture):
```
Please install nvidia proprietary drivers
Error code:2
```
![image](https://user-images.githubusercontent.com/43830391/101337852-7978eb80-387c-11eb-8dec-e261b60f8f2f.png)

but as you can also see in the picture i have the nvidia drivers installed. Have i missed something or is it a bug?

**Comment by RunGp** [comment]
nvidiux is no longer developed , i have no time to port this program to python3 and pyqt 5 ans support new card/drivers version
