### ISSUE TITLE
GTX 760 not supported

### ISSUE THREAD

**Issue by GabMus** [RunGp/Nvidiux#8]
As the title says, this GPU appears to be unsupported
The app works fine, tho. Overclocking works, as well as all readings, and the results are real (unigine heaven: 600pts stock, 630pts overclocked).
Wondering what makes it unsupported then.

**Comment by RunGp** [comment]
Hello 
Some users have reported to me that the turbo boost function is problematic on this card
What is the brand of your card ?

**Comment by GabMus** [comment]
It's an MSI Card, the box says overclock edition for some reason, but the
cooler is just a reference-style cooler. Nonetheless I managed to get to
1300 mhz with nvidiux and manage to stay under 81 °C.

**Comment by RunGp** [comment]
Ok
Next version i had your card in white list

**Comment by GabMus** [comment]
Thanks
